/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminSettingsPublic {
  'minWithdrawAmount' : bigint,
  'upiId' : string,
  'minDepositAmount' : bigint,
  'qrCode' : [] | [ExternalBlob],
}
export type BetId = bigint;
export interface BetRecordPublic {
  'id' : BetId,
  'betAmount' : bigint,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'gameType' : GameType,
  'playerChoice' : GameResult,
  'isWin' : boolean,
  'outcome' : GameResult,
  'payout' : bigint,
}
export interface DashboardStats {
  'totalPendingWithdrawals' : bigint,
  'totalApprovedDepositAmount' : bigint,
  'totalApprovedWithdrawalAmount' : bigint,
  'totalPendingDeposits' : bigint,
  'totalUsers' : bigint,
}
export type ExternalBlob = Uint8Array;
export type GameResult = { 'red' : null } |
  { 'tails' : null } |
  { 'heads' : null } |
  { 'dice' : bigint } |
  { 'black' : null };
export type GameType = { 'diceRoll' : null } |
  { 'coinFlip' : null } |
  { 'roulette' : null };
export type Result = { 'ok' : TransactionId } |
  { 'err' : string };
export type Result_1 = { 'ok' : null } |
  { 'err' : string };
export type Result_2 = { 'ok' : BetRecordPublic } |
  { 'err' : string };
export type Timestamp = bigint;
export type TransactionId = bigint;
export interface TransactionPublic {
  'id' : TransactionId,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'paymentProof' : [] | [ExternalBlob],
  'adminNote' : [] | [string],
  'withdrawalDestination' : [] | [WithdrawalDestination],
  'amount' : bigint,
}
export type TransactionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type TransactionType = { 'withdraw' : null } |
  { 'deposit' : null };
export interface UpdateAdminSettingsArgs {
  'minWithdrawAmount' : bigint,
  'upiId' : string,
  'minDepositAmount' : bigint,
  'qrCode' : [] | [ExternalBlob],
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'status' : UserStatus,
  'createdAt' : Timestamp,
  'walletBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'blocked' : null };
export interface WithdrawalDestination {
  'bankDetails' : [] | [string],
  'upiId' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminGetAllBets' : ActorMethod<[], Array<BetRecordPublic>>,
  'approveDeposit' : ActorMethod<[TransactionId, [] | [string]], Result_1>,
  'approveWithdrawal' : ActorMethod<[TransactionId, [] | [string]], Result_1>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[UserId], undefined>,
  'getAdminSettings' : ActorMethod<[], AdminSettingsPublic>,
  'getAllTransactions' : ActorMethod<[], Array<TransactionPublic>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyBets' : ActorMethod<[], Array<BetRecordPublic>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMyTransactions' : ActorMethod<[], Array<TransactionPublic>>,
  'getMyWalletBalance' : ActorMethod<[], bigint>,
  'getPendingDeposits' : ActorMethod<[], Array<TransactionPublic>>,
  'getPendingWithdrawals' : ActorMethod<[], Array<TransactionPublic>>,
  'getUser' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  /**
   * / Promote the caller to admin. Only works if no admin exists yet (first call).
   */
  'initializeAdmin' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBet' : ActorMethod<[GameType, bigint, GameResult], Result_2>,
  'registerUser' : ActorMethod<[], UserProfilePublic>,
  'rejectDeposit' : ActorMethod<[TransactionId, string], Result_1>,
  'rejectWithdrawal' : ActorMethod<[TransactionId, string], Result_1>,
  'requestDeposit' : ActorMethod<[bigint, ExternalBlob], Result>,
  'requestWithdrawal' : ActorMethod<[bigint, string, [] | [string]], Result>,
  'unblockUser' : ActorMethod<[UserId], undefined>,
  'updateAdminSettings' : ActorMethod<[UpdateAdminSettingsArgs], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];