/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BetId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const GameType = IDL.Variant({
  'diceRoll' : IDL.Null,
  'coinFlip' : IDL.Null,
  'roulette' : IDL.Null,
});
export const GameResult = IDL.Variant({
  'red' : IDL.Null,
  'tails' : IDL.Null,
  'heads' : IDL.Null,
  'dice' : IDL.Nat,
  'black' : IDL.Null,
});
export const BetRecordPublic = IDL.Record({
  'id' : BetId,
  'betAmount' : IDL.Nat,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'gameType' : GameType,
  'playerChoice' : GameResult,
  'isWin' : IDL.Bool,
  'outcome' : GameResult,
  'payout' : IDL.Nat,
});
export const TransactionId = IDL.Nat;
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdminSettingsPublic = IDL.Record({
  'minWithdrawAmount' : IDL.Nat,
  'upiId' : IDL.Text,
  'minDepositAmount' : IDL.Nat,
  'qrCode' : IDL.Opt(ExternalBlob),
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'withdraw' : IDL.Null,
  'deposit' : IDL.Null,
});
export const WithdrawalDestination = IDL.Record({
  'bankDetails' : IDL.Opt(IDL.Text),
  'upiId' : IDL.Text,
});
export const TransactionPublic = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'paymentProof' : IDL.Opt(ExternalBlob),
  'adminNote' : IDL.Opt(IDL.Text),
  'withdrawalDestination' : IDL.Opt(WithdrawalDestination),
  'amount' : IDL.Nat,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'blocked' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'createdAt' : Timestamp,
  'walletBalance' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'totalPendingWithdrawals' : IDL.Nat,
  'totalApprovedDepositAmount' : IDL.Nat,
  'totalApprovedWithdrawalAmount' : IDL.Nat,
  'totalPendingDeposits' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const Result_2 = IDL.Variant({
  'ok' : BetRecordPublic,
  'err' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : TransactionId, 'err' : IDL.Text });
export const UpdateAdminSettingsArgs = IDL.Record({
  'minWithdrawAmount' : IDL.Nat,
  'upiId' : IDL.Text,
  'minDepositAmount' : IDL.Nat,
  'qrCode' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminGetAllBets' : IDL.Func([], [IDL.Vec(BetRecordPublic)], []),
  'approveDeposit' : IDL.Func(
      [TransactionId, IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'approveWithdrawal' : IDL.Func(
      [TransactionId, IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([UserId], [], []),
  'getAdminSettings' : IDL.Func([], [AdminSettingsPublic], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(TransactionPublic)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyBets' : IDL.Func([], [IDL.Vec(BetRecordPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(TransactionPublic)], ['query']),
  'getMyWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingDeposits' : IDL.Func([], [IDL.Vec(TransactionPublic)], ['query']),
  'getPendingWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(TransactionPublic)],
      ['query'],
    ),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
  'initializeAdmin' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBet' : IDL.Func([GameType, IDL.Nat, GameResult], [Result_2], []),
  'registerUser' : IDL.Func([], [UserProfilePublic], []),
  'rejectDeposit' : IDL.Func([TransactionId, IDL.Text], [Result_1], []),
  'rejectWithdrawal' : IDL.Func([TransactionId, IDL.Text], [Result_1], []),
  'requestDeposit' : IDL.Func([IDL.Nat, ExternalBlob], [Result], []),
  'requestWithdrawal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'unblockUser' : IDL.Func([UserId], [], []),
  'updateAdminSettings' : IDL.Func([UpdateAdminSettingsArgs], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BetId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const GameType = IDL.Variant({
    'diceRoll' : IDL.Null,
    'coinFlip' : IDL.Null,
    'roulette' : IDL.Null,
  });
  const GameResult = IDL.Variant({
    'red' : IDL.Null,
    'tails' : IDL.Null,
    'heads' : IDL.Null,
    'dice' : IDL.Nat,
    'black' : IDL.Null,
  });
  const BetRecordPublic = IDL.Record({
    'id' : BetId,
    'betAmount' : IDL.Nat,
    'userId' : UserId,
    'timestamp' : Timestamp,
    'gameType' : GameType,
    'playerChoice' : GameResult,
    'isWin' : IDL.Bool,
    'outcome' : GameResult,
    'payout' : IDL.Nat,
  });
  const TransactionId = IDL.Nat;
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdminSettingsPublic = IDL.Record({
    'minWithdrawAmount' : IDL.Nat,
    'upiId' : IDL.Text,
    'minDepositAmount' : IDL.Nat,
    'qrCode' : IDL.Opt(ExternalBlob),
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'withdraw' : IDL.Null,
    'deposit' : IDL.Null,
  });
  const WithdrawalDestination = IDL.Record({
    'bankDetails' : IDL.Opt(IDL.Text),
    'upiId' : IDL.Text,
  });
  const TransactionPublic = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'paymentProof' : IDL.Opt(ExternalBlob),
    'adminNote' : IDL.Opt(IDL.Text),
    'withdrawalDestination' : IDL.Opt(WithdrawalDestination),
    'amount' : IDL.Nat,
  });
  const UserStatus = IDL.Variant({ 'active' : IDL.Null, 'blocked' : IDL.Null });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'createdAt' : Timestamp,
    'walletBalance' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'totalPendingWithdrawals' : IDL.Nat,
    'totalApprovedDepositAmount' : IDL.Nat,
    'totalApprovedWithdrawalAmount' : IDL.Nat,
    'totalPendingDeposits' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({ 'ok' : BetRecordPublic, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : TransactionId, 'err' : IDL.Text });
  const UpdateAdminSettingsArgs = IDL.Record({
    'minWithdrawAmount' : IDL.Nat,
    'upiId' : IDL.Text,
    'minDepositAmount' : IDL.Nat,
    'qrCode' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminGetAllBets' : IDL.Func([], [IDL.Vec(BetRecordPublic)], []),
    'approveDeposit' : IDL.Func(
        [TransactionId, IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'approveWithdrawal' : IDL.Func(
        [TransactionId, IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([UserId], [], []),
    'getAdminSettings' : IDL.Func([], [AdminSettingsPublic], ['query']),
    'getAllTransactions' : IDL.Func(
        [],
        [IDL.Vec(TransactionPublic)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyBets' : IDL.Func([], [IDL.Vec(BetRecordPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(TransactionPublic)], ['query']),
    'getMyWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingDeposits' : IDL.Func(
        [],
        [IDL.Vec(TransactionPublic)],
        ['query'],
      ),
    'getPendingWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(TransactionPublic)],
        ['query'],
      ),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
    'initializeAdmin' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBet' : IDL.Func([GameType, IDL.Nat, GameResult], [Result_2], []),
    'registerUser' : IDL.Func([], [UserProfilePublic], []),
    'rejectDeposit' : IDL.Func([TransactionId, IDL.Text], [Result_1], []),
    'rejectWithdrawal' : IDL.Func([TransactionId, IDL.Text], [Result_1], []),
    'requestDeposit' : IDL.Func([IDL.Nat, ExternalBlob], [Result], []),
    'requestWithdrawal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'unblockUser' : IDL.Func([UserId], [], []),
    'updateAdminSettings' : IDL.Func([UpdateAdminSettingsArgs], [], []),
  });
};

export const init = ({ IDL }) => { return []; };