/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransactionPublic {
    id: TransactionId;
    status: TransactionStatus;
    transactionType: TransactionType;
    userId: UserId;
    createdAt: Timestamp;
    paymentProof?: ExternalBlob;
    adminNote?: string;
    withdrawalDestination?: WithdrawalDestination;
    amount: bigint;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: BetRecordPublic;
} | {
    __kind__: "err";
    err: string;
};
export type BetId = bigint;
export interface AdminSettingsPublic {
    minWithdrawAmount: bigint;
    upiId: string;
    minDepositAmount: bigint;
    qrCode?: ExternalBlob;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface UserProfilePublic {
    id: UserId;
    status: UserStatus;
    createdAt: Timestamp;
    walletBalance: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface DashboardStats {
    totalPendingWithdrawals: bigint;
    totalApprovedDepositAmount: bigint;
    totalApprovedWithdrawalAmount: bigint;
    totalPendingDeposits: bigint;
    totalUsers: bigint;
}
export type UserId = Principal;
export type TransactionId = bigint;
export type Result = {
    __kind__: "ok";
    ok: TransactionId;
} | {
    __kind__: "err";
    err: string;
};
export interface UpdateAdminSettingsArgs {
    minWithdrawAmount: bigint;
    upiId: string;
    minDepositAmount: bigint;
    qrCode?: ExternalBlob;
}
export interface BetRecordPublic {
    id: BetId;
    betAmount: bigint;
    userId: UserId;
    timestamp: Timestamp;
    gameType: GameType;
    playerChoice: GameResult;
    isWin: boolean;
    outcome: GameResult;
    payout: bigint;
}
export type GameResult = {
    __kind__: "red";
    red: null;
} | {
    __kind__: "tails";
    tails: null;
} | {
    __kind__: "heads";
    heads: null;
} | {
    __kind__: "dice";
    dice: bigint;
} | {
    __kind__: "black";
    black: null;
};
export interface WithdrawalDestination {
    bankDetails?: string;
    upiId: string;
}
export enum GameType {
    diceRoll = "diceRoll",
    coinFlip = "coinFlip",
    roulette = "roulette"
}
export enum TransactionStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum TransactionType {
    withdraw = "withdraw",
    deposit = "deposit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    blocked = "blocked"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    adminGetAllBets(): Promise<Array<BetRecordPublic>>;
    approveDeposit(txId: TransactionId, note: string | null): Promise<Result_1>;
    approveWithdrawal(txId: TransactionId, note: string | null): Promise<Result_1>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(userId: UserId): Promise<void>;
    getAdminSettings(): Promise<AdminSettingsPublic>;
    getAllTransactions(): Promise<Array<TransactionPublic>>;
    getAllUsers(): Promise<Array<UserProfilePublic>>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getMyBets(): Promise<Array<BetRecordPublic>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getMyTransactions(): Promise<Array<TransactionPublic>>;
    getMyWalletBalance(): Promise<bigint>;
    getPendingDeposits(): Promise<Array<TransactionPublic>>;
    getPendingWithdrawals(): Promise<Array<TransactionPublic>>;
    getUser(userId: UserId): Promise<UserProfilePublic | null>;
    /**
     * / Promote the caller to admin. Only works if no admin exists yet (first call).
     */
    initializeAdmin(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    placeBet(gameType: GameType, betAmount: bigint, playerChoice: GameResult): Promise<Result_2>;
    registerUser(): Promise<UserProfilePublic>;
    rejectDeposit(txId: TransactionId, note: string): Promise<Result_1>;
    rejectWithdrawal(txId: TransactionId, note: string): Promise<Result_1>;
    requestDeposit(amount: bigint, paymentProof: ExternalBlob): Promise<Result>;
    requestWithdrawal(amount: bigint, upiId: string, bankDetails: string | null): Promise<Result>;
    unblockUser(userId: UserId): Promise<void>;
    updateAdminSettings(args: UpdateAdminSettingsArgs): Promise<void>;
}
import type { AdminSettingsPublic as _AdminSettingsPublic, BetId as _BetId, BetRecordPublic as _BetRecordPublic, ExternalBlob as _ExternalBlob, GameResult as _GameResult, GameType as _GameType, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Timestamp as _Timestamp, TransactionId as _TransactionId, TransactionPublic as _TransactionPublic, TransactionStatus as _TransactionStatus, TransactionType as _TransactionType, UpdateAdminSettingsArgs as _UpdateAdminSettingsArgs, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, UserStatus as _UserStatus, WithdrawalDestination as _WithdrawalDestination, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminGetAllBets(): Promise<Array<BetRecordPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllBets();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllBets();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveDeposit(arg0: TransactionId, arg1: string | null): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDeposit(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDeposit(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveWithdrawal(arg0: TransactionId, arg1: string | null): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async getAdminSettings(): Promise<AdminSettingsPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminSettings();
                return from_candid_AdminSettingsPublic_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminSettings();
            return from_candid_AdminSettingsPublic_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<TransactionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMyBets(): Promise<Array<BetRecordPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBets();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBets();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<TransactionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWalletBalance();
            return result;
        }
    }
    async getPendingDeposits(): Promise<Array<TransactionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDeposits();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDeposits();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingWithdrawals(): Promise<Array<TransactionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingWithdrawals();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingWithdrawals();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeBet(arg0: GameType, arg1: bigint, arg2: GameResult): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBet(to_candid_GameType_n43(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_GameResult_n45(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_2_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBet(to_candid_GameType_n43(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_GameResult_n45(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_2_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser();
                return from_candid_UserProfilePublic_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser();
            return from_candid_UserProfilePublic_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectDeposit(arg0: TransactionId, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDeposit(arg0, arg1);
                return from_candid_Result_1_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDeposit(arg0, arg1);
            return from_candid_Result_1_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectWithdrawal(arg0: TransactionId, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0, arg1);
                return from_candid_Result_1_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0, arg1);
            return from_candid_Result_1_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestDeposit(arg0: bigint, arg1: ExternalBlob): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.requestDeposit(arg0, await to_candid_ExternalBlob_n49(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestDeposit(arg0, await to_candid_ExternalBlob_n49(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestWithdrawal(arg0: bigint, arg1: string, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async unblockUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateAdminSettings(arg0: UpdateAdminSettingsArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminSettings(await to_candid_UpdateAdminSettingsArgs_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminSettings(await to_candid_UpdateAdminSettingsArgs_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_AdminSettingsPublic_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminSettingsPublic): Promise<AdminSettingsPublic> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_BetRecordPublic_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BetRecordPublic): BetRecordPublic {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GameResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameResult): GameResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_GameType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameType): GameType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_TransactionPublic_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionPublic): Promise<TransactionPublic> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalDestination_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalDestination): WithdrawalDestination {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WithdrawalDestination]): WithdrawalDestination | null {
    return value.length === 0 ? null : from_candid_WithdrawalDestination_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BetId;
    betAmount: bigint;
    userId: _UserId;
    timestamp: _Timestamp;
    gameType: _GameType;
    playerChoice: _GameResult;
    isWin: boolean;
    outcome: _GameResult;
    payout: bigint;
}): {
    id: BetId;
    betAmount: bigint;
    userId: UserId;
    timestamp: Timestamp;
    gameType: GameType;
    playerChoice: GameResult;
    isWin: boolean;
    outcome: GameResult;
    payout: bigint;
} {
    return {
        id: value.id,
        betAmount: value.betAmount,
        userId: value.userId,
        timestamp: value.timestamp,
        gameType: from_candid_GameType_n11(_uploadFile, _downloadFile, value.gameType),
        playerChoice: from_candid_GameResult_n13(_uploadFile, _downloadFile, value.playerChoice),
        isWin: value.isWin,
        outcome: from_candid_GameResult_n13(_uploadFile, _downloadFile, value.outcome),
        payout: value.payout
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minWithdrawAmount: bigint;
    upiId: string;
    minDepositAmount: bigint;
    qrCode: [] | [_ExternalBlob];
}): Promise<{
    minWithdrawAmount: bigint;
    upiId: string;
    minDepositAmount: bigint;
    qrCode?: ExternalBlob;
}> {
    return {
        minWithdrawAmount: value.minWithdrawAmount,
        upiId: value.upiId,
        minDepositAmount: value.minDepositAmount,
        qrCode: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.qrCode))
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    status: _TransactionStatus;
    transactionType: _TransactionType;
    userId: _UserId;
    createdAt: _Timestamp;
    paymentProof: [] | [_ExternalBlob];
    adminNote: [] | [string];
    withdrawalDestination: [] | [_WithdrawalDestination];
    amount: bigint;
}): Promise<{
    id: TransactionId;
    status: TransactionStatus;
    transactionType: TransactionType;
    userId: UserId;
    createdAt: Timestamp;
    paymentProof?: ExternalBlob;
    adminNote?: string;
    withdrawalDestination?: WithdrawalDestination;
    amount: bigint;
}> {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n27(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_TransactionType_n29(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        createdAt: value.createdAt,
        paymentProof: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.paymentProof)),
        adminNote: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.adminNote)),
        withdrawalDestination: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.withdrawalDestination)),
        amount: value.amount
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankDetails: [] | [string];
    upiId: string;
}): {
    bankDetails?: string;
    upiId: string;
} {
    return {
        bankDetails: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.bankDetails)),
        upiId: value.upiId
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    createdAt: _Timestamp;
    walletBalance: bigint;
}): {
    id: UserId;
    status: UserStatus;
    createdAt: Timestamp;
    walletBalance: bigint;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n38(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diceRoll: null;
} | {
    coinFlip: null;
} | {
    roulette: null;
}): GameType {
    return "diceRoll" in value ? GameType.diceRoll : "coinFlip" in value ? GameType.coinFlip : "roulette" in value ? GameType.roulette : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    tails: null;
} | {
    heads: null;
} | {
    dice: bigint;
} | {
    black: null;
}): {
    __kind__: "red";
    red: null;
} | {
    __kind__: "tails";
    tails: null;
} | {
    __kind__: "heads";
    heads: null;
} | {
    __kind__: "dice";
    dice: bigint;
} | {
    __kind__: "black";
    black: null;
} {
    return "red" in value ? {
        __kind__: "red",
        red: value.red
    } : "tails" in value ? {
        __kind__: "tails",
        tails: value.tails
    } : "heads" in value ? {
        __kind__: "heads",
        heads: value.heads
    } : "dice" in value ? {
        __kind__: "dice",
        dice: value.dice
    } : "black" in value ? {
        __kind__: "black",
        black: value.black
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "approved" in value ? TransactionStatus.approved : "rejected" in value ? TransactionStatus.rejected : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdraw: null;
} | {
    deposit: null;
}): TransactionType {
    return "withdraw" in value ? TransactionType.withdraw : "deposit" in value ? TransactionType.deposit : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    blocked: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "blocked" in value ? UserStatus.blocked : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BetRecordPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BetRecordPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BetRecordPublic_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TransactionId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TransactionId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionPublic>): Promise<Array<TransactionPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TransactionPublic_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfilePublic>): Array<UserProfilePublic> {
    return value.map((x)=>from_candid_UserProfilePublic_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BetRecordPublic>): Array<BetRecordPublic> {
    return value.map((x)=>from_candid_BetRecordPublic_n9(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GameResult_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameResult): _GameResult {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_GameType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): _GameType {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateAdminSettingsArgs_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateAdminSettingsArgs): Promise<_UpdateAdminSettingsArgs> {
    return await to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minWithdrawAmount: bigint;
    upiId: string;
    minDepositAmount: bigint;
    qrCode?: ExternalBlob;
}): Promise<{
    minWithdrawAmount: bigint;
    upiId: string;
    minDepositAmount: bigint;
    qrCode: [] | [_ExternalBlob];
}> {
    return {
        minWithdrawAmount: value.minWithdrawAmount,
        upiId: value.upiId,
        minDepositAmount: value.minDepositAmount,
        qrCode: value.qrCode ? candid_some(await to_candid_ExternalBlob_n49(_uploadFile, _downloadFile, value.qrCode)) : candid_none()
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): {
    diceRoll: null;
} | {
    coinFlip: null;
} | {
    roulette: null;
} {
    return value == GameType.diceRoll ? {
        diceRoll: null
    } : value == GameType.coinFlip ? {
        coinFlip: null
    } : value == GameType.roulette ? {
        roulette: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "red";
    red: null;
} | {
    __kind__: "tails";
    tails: null;
} | {
    __kind__: "heads";
    heads: null;
} | {
    __kind__: "dice";
    dice: bigint;
} | {
    __kind__: "black";
    black: null;
}): {
    red: null;
} | {
    tails: null;
} | {
    heads: null;
} | {
    dice: bigint;
} | {
    black: null;
} {
    return value.__kind__ === "red" ? {
        red: value.red
    } : value.__kind__ === "tails" ? {
        tails: value.tails
    } : value.__kind__ === "heads" ? {
        heads: value.heads
    } : value.__kind__ === "dice" ? {
        dice: value.dice
    } : value.__kind__ === "black" ? {
        black: value.black
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
